services:
  web:
    container_name: vl-web
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/localhost/htdocs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  redis:
    container_name: vl-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
  db:
    container_name: vl-db
    image: mariadb:10.6.16
    volumes:
      - ./.db:/var/lib/mysql
      - .docker/db_test.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - "3306:3306"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_DATABASE: visao_libertaria
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 20s
