server {
    listen 80;
    server_name localhost;
    root /var/www/localhost/htdocs;
    index index.php;

    client_max_body_size 12m;

    gzip on;
    gzip_vary on;
    gzip_types text/css application/javascript application/json image/svg+xml font/woff2;

    location = /favicon.ico {
        alias /var/www/localhost/htdocs/public/assets/favicon.ico;
        access_log off;
        expires 1y;
        add_header Cache-Control "public";
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass web:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~* \.(css|js)$ {
        expires 1M;
        add_header Cache-Control "public";
        access_log off;
    }

    location ~* \.(jpe?g|png|gif|ico|webp|svg|woff2?|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public";
        access_log off;
    }
}
